repos:
  - repo: https://github.com/syntaqx/git-hooks
    rev: master
    hooks:
      - id: circleci-config-validate
      - id: forbid-binary
      - id: shellcheck
  - repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v3.3.0
    hooks:
      - id: detect-private-key
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-executables-have-shebangs
      - id: detect-private-key
      - id: forbid-new-submodules
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-xml
      - id: check-json
      - id: check-ast
      - id: name-tests-test

